title: SystemMonitor
description: SystemMonitor is a system monitoring application that can run on every Desktop OS with a single code and single executable.
show_downloads: false
theme: jekyll-theme-minimal
