title: Currency Manager
description: Currency Manager is a simple program that gathers currency rates from Fixer.io and makes calculations in between currencies and shows rate tables.
show_downloads: false
theme: jekyll-theme-minimal
